# Generated by Django 3.0.4 on 2020-03-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('expected_gpu', models.IntegerField()),
                ('expected_gpu_speed', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
