# Generated by Django 3.0.4 on 2020-03-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
